spring:
 datasource:
  druid:
    db1:
      url: jdbc:mysql://10.0.10.98:3306/smallbun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
    filter:
      slf4j:
        data-source-log-enabled: true
  #  db2:
  #    url: jdbc:oracle:thin:@192.168.136.222:ORCL
  #    username: sa
  #    password: sa123456
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    initialSize: 5
  #    minIdle: 5
  #    maxActive: 20
  #    db3:
  #      url: jdbc:oracle:thin:@192.168.136.223:ORCL
  #      username: sb
  #      password: sb123456
  #      driver-class-name: oracle.jdbc.OracleDriver
  #      initialSize: 5
  #      minIdle: 5
  #      maxActive: 20